# Generated by Django 3.0.8 on 2020-07-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=500)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('altphone', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=200)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdates',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=1000)),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
